# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName("AppWindow")
        AppWindow.resize(745, 520)
        self.centralwidget = QtWidgets.QWidget(AppWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 0, 641, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.user_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.user_data_button.setGeometry(QtCore.QRect(0, 0, 101, 41))
        self.user_data_button.setObjectName("user_data_button")
        self.payment_button = QtWidgets.QPushButton(self.centralwidget)
        self.payment_button.setGeometry(QtCore.QRect(0, 40, 101, 41))
        self.payment_button.setObjectName("payment_button")
        self.tariff_button = QtWidgets.QPushButton(self.centralwidget)
        self.tariff_button.setGeometry(QtCore.QRect(0, 80, 101, 41))
        self.tariff_button.setObjectName("tariff_button")
        self.tariff_period_button = QtWidgets.QPushButton(self.centralwidget)
        self.tariff_period_button.setGeometry(QtCore.QRect(0, 120, 101, 41))
        self.tariff_period_button.setObjectName("tariff_period_button")
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(100, 420, 101, 51))
        self.select_button.setObjectName("select_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(200, 420, 101, 51))
        self.add_button.setObjectName("add_button")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(300, 420, 101, 51))
        self.update_button.setObjectName("update_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(400, 420, 101, 51))
        self.delete_button.setObjectName("delete_button")
        self.task_button = QtWidgets.QPushButton(self.centralwidget)
        self.task_button.setGeometry(QtCore.QRect(0, 160, 101, 41))
        self.task_button.setObjectName("task_button")
        AppWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AppWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menubar.setObjectName("menubar")
        AppWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AppWindow)
        self.statusbar.setObjectName("statusbar")
        AppWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AppWindow)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        _translate = QtCore.QCoreApplication.translate
        AppWindow.setWindowTitle(_translate("AppWindow", "MainWindow"))
        self.user_data_button.setText(_translate("AppWindow", "user_data"))
        self.payment_button.setText(_translate("AppWindow", "payment"))
        self.tariff_button.setText(_translate("AppWindow", "tariff"))
        self.tariff_period_button.setText(_translate("AppWindow", "tariff_period"))
        self.select_button.setText(_translate("AppWindow", "обновить"))
        self.add_button.setText(_translate("AppWindow", "добавить"))
        self.update_button.setText(_translate("AppWindow", "изменить"))
        self.delete_button.setText(_translate("AppWindow", "удалить"))
        self.task_button.setText(_translate("AppWindow", "задания"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppWindow = QtWidgets.QMainWindow()
    ui = Ui_AppWindow()
    ui.setupUi(AppWindow)
    AppWindow.show()
    sys.exit(app.exec_())
