# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_payment_window(object):
    def setupUi(self, delete_payment_window):
        delete_payment_window.setObjectName("delete_payment_window")
        delete_payment_window.resize(252, 147)
        self.centralwidget = QtWidgets.QWidget(delete_payment_window)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_payment_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_payment_button.setGeometry(QtCore.QRect(120, 50, 91, 41))
        self.delete_payment_button.setObjectName("delete_payment_button")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_payment_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_payment_id.setGeometry(QtCore.QRect(80, 10, 131, 20))
        self.lineEdit_payment_id.setObjectName("lineEdit_payment_id")
        delete_payment_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_payment_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 21))
        self.menubar.setObjectName("menubar")
        delete_payment_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_payment_window)
        self.statusbar.setObjectName("statusbar")
        delete_payment_window.setStatusBar(self.statusbar)

        self.retranslateUi(delete_payment_window)
        QtCore.QMetaObject.connectSlotsByName(delete_payment_window)

    def retranslateUi(self, delete_payment_window):
        _translate = QtCore.QCoreApplication.translate
        delete_payment_window.setWindowTitle(_translate("delete_payment_window", "MainWindow"))
        self.delete_payment_button.setText(_translate("delete_payment_window", "delete_payment"))
        self.label_7.setText(_translate("delete_payment_window", "payment_id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_payment_window = QtWidgets.QMainWindow()
    ui = Ui_delete_payment_window()
    ui.setupUi(delete_payment_window)
    delete_payment_window.show()
    sys.exit(app.exec_())
