# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_user_window(object):
    def setupUi(self, delete_user_window):
        delete_user_window.setObjectName("delete_user_window")
        delete_user_window.resize(252, 147)
        self.centralwidget = QtWidgets.QWidget(delete_user_window)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_user_button.setGeometry(QtCore.QRect(130, 50, 81, 41))
        self.delete_user_button.setObjectName("delete_user_button")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_user_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_user_id.setGeometry(QtCore.QRect(80, 10, 131, 20))
        self.lineEdit_user_id.setObjectName("lineEdit_user_id")
        delete_user_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_user_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 21))
        self.menubar.setObjectName("menubar")
        delete_user_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_user_window)
        self.statusbar.setObjectName("statusbar")
        delete_user_window.setStatusBar(self.statusbar)

        self.retranslateUi(delete_user_window)
        QtCore.QMetaObject.connectSlotsByName(delete_user_window)

    def retranslateUi(self, delete_user_window):
        _translate = QtCore.QCoreApplication.translate
        delete_user_window.setWindowTitle(_translate("delete_user_window", "MainWindow"))
        self.delete_user_button.setText(_translate("delete_user_window", "delete_user"))
        self.label_7.setText(_translate("delete_user_window", "user_id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_user_window = QtWidgets.QMainWindow()
    ui = Ui_delete_user_window()
    ui.setupUi(delete_user_window)
    delete_user_window.show()
    sys.exit(app.exec_())
