# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_tariff_period.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_tariff_period_window(object):
    def setupUi(self, delete_tariff_period_window):
        delete_tariff_period_window.setObjectName("delete_tariff_period_window")
        delete_tariff_period_window.resize(252, 147)
        self.centralwidget = QtWidgets.QWidget(delete_tariff_period_window)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_tariff_period_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_tariff_period_button.setGeometry(QtCore.QRect(120, 50, 111, 41))
        self.delete_tariff_period_button.setObjectName("delete_tariff_period_button")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_tariff_period_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tariff_period_id.setGeometry(QtCore.QRect(100, 10, 131, 20))
        self.lineEdit_tariff_period_id.setObjectName("lineEdit_tariff_period_id")
        delete_tariff_period_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_tariff_period_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 21))
        self.menubar.setObjectName("menubar")
        delete_tariff_period_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_tariff_period_window)
        self.statusbar.setObjectName("statusbar")
        delete_tariff_period_window.setStatusBar(self.statusbar)

        self.retranslateUi(delete_tariff_period_window)
        QtCore.QMetaObject.connectSlotsByName(delete_tariff_period_window)

    def retranslateUi(self, delete_tariff_period_window):
        _translate = QtCore.QCoreApplication.translate
        delete_tariff_period_window.setWindowTitle(_translate("delete_tariff_period_window", "MainWindow"))
        self.delete_tariff_period_button.setText(_translate("delete_tariff_period_window", "delete_tariff_period"))
        self.label_7.setText(_translate("delete_tariff_period_window", "tariff_period_id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_tariff_period_window = QtWidgets.QMainWindow()
    ui = Ui_delete_tariff_period_window()
    ui.setupUi(delete_tariff_period_window)
    delete_tariff_period_window.show()
    sys.exit(app.exec_())
