# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication

from test import Database


class Ui_update_view_window(object):
    def setupUi(self, update_view_window):
        update_view_window.setObjectName("update_view_window")
        update_view_window.resize(499, 261)
        self.centralwidget = QtWidgets.QWidget(update_view_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 50, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_payment_date = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_payment_date.setGeometry(QtCore.QRect(110, 50, 131, 20))
        self.lineEdit_payment_date.setObjectName("lineEdit_payment_date")
        self.lineEdit_start_date = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_start_date.setGeometry(QtCore.QRect(110, 10, 131, 20))
        self.lineEdit_start_date.setObjectName("lineEdit_start_date")
        self.lineEdit_payment_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_payment_amount.setGeometry(QtCore.QRect(350, 50, 131, 20))
        self.lineEdit_payment_amount.setObjectName("lineEdit_payment_amount")
        self.lineEdit_end_date = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_end_date.setGeometry(QtCore.QRect(350, 10, 131, 20))
        self.lineEdit_end_date.setObjectName("lineEdit_end_date")
        self.update_view_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_view_button.setGeometry(QtCore.QRect(380, 170, 101, 41))
        self.update_view_button.setObjectName("update_view_button")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 91, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_payment_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_payment_id.setGeometry(QtCore.QRect(110, 170, 131, 20))
        self.lineEdit_payment_id.setObjectName("lineEdit_payment_id")
        self.lineEdit_surname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_surname.setGeometry(QtCore.QRect(350, 90, 131, 20))
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.label_6.setObjectName("label_6")
        self.lineEdit_price = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_price.setGeometry(QtCore.QRect(110, 90, 131, 20))
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 90, 91, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_middle_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_middle_name.setGeometry(QtCore.QRect(350, 130, 131, 20))
        self.lineEdit_middle_name.setObjectName("lineEdit_middle_name")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 91, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_first_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_first_name.setGeometry(QtCore.QRect(110, 130, 131, 20))
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 130, 91, 20))
        self.label_9.setObjectName("label_9")
        update_view_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(update_view_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 21))
        self.menubar.setObjectName("menubar")
        update_view_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(update_view_window)
        self.statusbar.setObjectName("statusbar")
        update_view_window.setStatusBar(self.statusbar)

        self.retranslateUi(update_view_window)
        QtCore.QMetaObject.connectSlotsByName(update_view_window)

    def retranslateUi(self, update_view_window):
        _translate = QtCore.QCoreApplication.translate
        update_view_window.setWindowTitle(_translate("update_view_window", "MainWindow"))
        self.label.setText(_translate("update_view_window", "start_date"))
        self.label_2.setText(_translate("update_view_window", "payment_date"))
        self.label_3.setText(_translate("update_view_window", "payment_amount"))
        self.label_4.setText(_translate("update_view_window", "end_date"))
        self.update_view_button.setText(_translate("update_view_window", "update_view"))
        self.label_5.setText(_translate("update_view_window", "payment_id"))
        self.label_6.setText(_translate("update_view_window", "price"))
        self.label_7.setText(_translate("update_view_window", "surname"))
        self.label_8.setText(_translate("update_view_window", "first_name"))
        self.label_9.setText(_translate("update_view_window", "middle_name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_payment_window = QtWidgets.QMainWindow()
    ui = Ui_update_view_window()
    ui.setupUi(update_payment_window)
    update_payment_window.show()
    sys.exit(app.exec_())
